PERSON_STATUS_COLORS = {
  'n/a' => nil,
  'Pinged, no response' => 'grey',
  'Discussing an opportunity' => '#FFF2CC',
  'Not interested' => 'orange',
  'Not interested, on hold' => 'orange',
  'Interested, ping later' => 'yellow',
  'Interested, on hold' => 'yellow',
  'Initial interview' => '#CC99CC',
  'Technical interview' => '#816687',
  'Additional interview' => '#A74CAB',
  'Interview with CEO' => '#CD96CD',
  'Test assignment' => '#EE82EE',
  'Rejected, no go' => '#EB5E66',
  'Rejected, on hold' => '#FFAEB9',
  'Hired' => 'green',
}
