PERSON_STATUS_COLORS = {
  'n/a' => nil,
  'Pinged, no response' => 'grey',
  'Discussing an opportunity' => '#FFF2CC',
  'Not interested' => 'orange',
  'Not interested, on hold' => 'orange',
  'Interested, ping later' => 'yellow',
  'Interested, on hold' => 'yellow',
  'Initial interview' => 'purple',
  'Technical interview' => 'purple',
  'Additional interview' => 'purple',
  'Interview with CEO' => 'purple',
  'Test assignment' => 'purple',
  'Rejected, no go' => 'red',
  'Rejected, on hold' => 'orange',
  'Hired' => 'green',
}
