p1 = Person.create(name: 'Vasiliy Pupkin')
n1 = Note.create(person: p1, type: 'Decision', value: "Let's hire him")
n2 = Note.create(person: p1, type: 'Expected Salary', value: "500")
a1 = Assessment.create(person: p1, value: '{"Ruby": 9}', total: 9)
a2 = Assessment.create(person: p1, value: '{"DB": 7}', total: 7)
ap1 = ActionPoint.create(person: p1, value: 'Meet in a cafe', perform_on: Date.tomorrow)
ap2 = ActionPoint.create(person: p1, value: 'Hire', perform_on: Date.tomorrow)
